{% set name = "gz-sim-robotraconteur-plugins" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/robotraconteur-contrib/gz-sim-robotraconteur-plugins/archive/c4c0004261f012fc5ab386171ff3fd43f3266d1c.tar.gz
  sha256: 066842324099b2a9ee7363713c022016384d44569a8edf702fdd992356f1054c

build:
  number: 2

requirements:
  build:
    - git
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - librobotraconteur                         # [build_platform != target_platform]
    - gz-cmake3
  host:
    - librobotraconteur >=1.2.7
    - robotraconteur_companion >=0.4.2
    - libgz-sim
    - libboost-devel
    - yaml-cpp
    - eigen
    - pkgconfig
    - libblas
    - tinyxml2

about:
  home: https://github.com/robotraconteur-contrib/gz-sim-robotraconteur-plugins
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Robot Raconteur plugin for the GZ Sim Robot Simulator'

extra:
  recipe-maintainers:
    - johnwason
